"""empty message

Revision ID: 1812b77bbbf0
Revises: c4b47c5d8858
Create Date: 2024-05-25 10:21:36.435805

"""
from typing import Sequence, Union
import db.types
from models import enums
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1812b77bbbf0'
down_revision: Union[str, None] = 'c4b47c5d8858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=20), nullable=False),
    sa.Column('guest_team', sa.String(length=20), nullable=False),
    sa.Column('refs', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('date_start', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament')
    op.drop_table('match')
    # ### end Alembic commands ###
