"""empty message

Revision ID: c4b47c5d8858
Revises: 8769d0c53650
Create Date: 2024-05-24 15:03:17.874923

"""
from typing import Sequence, Union
import db.types
from models import enums
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b47c5d8858'
down_revision: Union[str, None] = '8769d0c53650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
